### ISSUE TITLE
v512 4.3J System Menu Hacks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DacoTaco/priiloader#198]
```
For several months, some of the hacks for this system menu didn't work (such as 
region free everything, no system menu sounds, etc.). I tried using the latest 
version of Priiloader, but this gave no different results. So today, i tried 
using an older version of Priiloader, which was v0.3b. I used the 4.3J hacks 
from the Preloader/hacks page on WiiBrew, and miraculously they worked. With 
this in mind, is there a way to make the hacks work with the current Priiloader 
version?
```

Original issue reported on code.google.com by `cae...@yahoo.com` on 9 Jun 2014 at 12:01

**Comment by Jasjar42** [comment]
I checked a few of the hacks on on 4.3J. Results are;
```
[region free everything] The 4.3J patch on this page works. Haven't tested gc yet.

[Auto press A] Works

[Remove NoCopy save file] Partially works. Copy button works, but move button doesn't.

[move disk menu] Works

[replace heath screen with backmenu] Like a "reboot" at the start. I guess this is the intention?

[Lock system menu with black screen] Works

[Force standard recovery mode] Works

[Force disks under IOS249] Seems like it works

[block online update] Works

**Comment by DacoTaco** [comment]
i could kiss you for testing and working on this :P 

some hacks like the remove nocopy is probably the result of a partial patch (aka, a hash that is wrong). but the others work so thats bueno's !

i updated the wiibrew page to reflect the region free thing

**Comment by Karma1233** [comment]
I'm having issues installing Priiloader. I think maybe it's because I have a Japanese Wii 4.3J

I've seen a lot of issues regarding 4.3J, but everyone else seems to get it to work. I can't get Priiloader to show up at all. It says it has installed/updated, but upon Power On and holding Reset, It never shows up. I'm not on GitHub that often due to work/life, so if at all possible, please reach out to me on Discord. My handle is Karma#9033. Thanks a million in advance.

**Comment by DacoTaco** [comment]
@Karma1233 i tried looking you up on discord but didn't find you. hence this comment.

does it show a black screen when holding the reset or does it go straight to system menu?
try booting the loadpriiloader.dol from homebrew channel found in the extra folder of the release zip.

**Comment by Karma1233** [comment]
So when I create a new account on Discord, go to my friends tab, Add Friend, and type in Karma#9033, it sends a request to me without issue. Maybe something wrong on your end?

Regardless,
When I install Priiloader, Power Off (Red light on Wii), Power On, quickly press and hold Reset, it (previously) goes directly to BootMii. Ever since 2 days ago, I get the bug where I have to reset my Wii to power on. Priiloader has screwed my system, even after an uninstall. I assume I'll need to reinstall BootMii.

When I get the chance, I will try booting the loadpriiloader dol from the Homebrew Channel. Thanks for the help.

**Comment by DacoTaco** [comment]
ill look into discord and why its not finding you, maybe update it too.

untill then, let me sum up everything 

- system needs to be fully shut down or it doesn't boot system menu (regular orange light shutdown and then power on doesn't boot system menu)
- when holding reset it doesn't boot priiloader 

this is it? 
from the sound of it the loadpriiloader dol won't work, but you can try.
also, what system menu and priiloader is installed? bootmii @ boot2 ? what did you change 2 days ago?

**Comment by Karma1233** [comment]
Yeah that's basically it. When I boot from Orange or Red, I get nothing on the screen. I have to press Reset afterwards to get to the Wii System Menu.

I had BootMii installed as Boot2. I changed nothing. Went to bed, woke up, didn't work. Lol. Was confused. Holding Reset does not boot into Priiloader either from Red or Orange. I should have been more specific about that part.

I'm on site right now, so I can't try anything, but when I get home tonight, I'll fiddle with it and see if I can get something to work. I'm a programmer, but mainly in C#/C++ and I have no experience with NAND or Wii stuff. Otherwise, I'd just fix this myself. Rather talk to the professionals before I tinker with anything that might brick my wii. I did do a backup of my Wii via BootMii a while ago, so I should be safe, I think.

**Comment by DacoTaco** [comment]
if you have bootmii@boot2 then thats a good thing. from the sound of it either priiloader is crashing somewhere (i hope) or system menu is broken (less likely. otherwise it just wouldn't boot). i doubt something killed it suddenly though...

i recommend making a nand backup using bootmii, or verifying that backup you had, before doing anything, just in case something happens along the way (better safe then sorry)

when you hold reset , does it give a black screen? or does it boot system menu?
if it gives a black screen, then i think priiloader crashed.
if it boots system menu, and the loadpriiloader dol does nothing, then i think priiloader is not installed.

i wouldn't switch the SM version to the 4.3U version, that would be useless and do more harm then good. 
there is a few things we can do to troubleshoot the state of the wii though. we can compare a few app files on the system nand to verify. for this we'd need /title/00000001/00000002/content/00000055.app & 10000055.app (if it exists)
and also /title/00000001/00000002/data/loader.ini if it exists.
this can be done using an homebrew application like https://wiibrew.org/wiki/FS_Browser
using those files i can determine if priiloader is installed correctly, what version and what your settings are and if the system menu booting file is still intact.

overall i think reinstalling the system menu ( 4.3J) and reinstalling priiloader will fix it, but i'd rather know what is wrong before then.
