### ISSUE TITLE
Cannot use priiloader after reset/format

### ISSUE THREAD

**Issue by jacko141** [DacoTaco/priiloader#210]
Hi,
I have a WII version 4.1E with priiloader 0.7 and activated homebrew. 
The remotes stopped working and to reuse them I tried to resync without success, so I followed the recommendation to format system data. 
Now the remotes work again, but I can neither reinstall homebrew nor launch priiloader.
Is priiloader still in the background after format? I couldn't start it with pressing the reset button on startup.
Any suggestions what I can do to reactivate these hacks?

**Comment by DacoTaco** [comment]
afaik, after a format it reinstalls and updates the system menu, please verify this in the System menu settings (it should show the version)

it also causes priiloader to be removed, since system menu is reinstalled and you'll have to reinstall everything using one of the 4.3 exploits shown on the wiibrew page : http://wiibrew.org/wiki/System_Menu_4.3
