### ISSUE TITLE
Updating Priiloader

### ISSUE THREAD

**Issue by stefa168** [DacoTaco/priiloader#298]
Hi, sorry for the new issue, but I couldn't find this information anywhere.

After years that I modded my wii I found out (via openshop) that there has been a new release of priiloader. What should be the correct way to update priiloader on my wii? Should I just run the installer and install?

Thanks!

**Comment by DacoTaco** [comment]
normally i would advise to use the in menu updater, but it due to my host changing something it has been broken on anything < 0.10 (beta 1).

a good way to update is the download priiloader again, put it on sd and run the installer again. after that, enter the priiloader menu and set it up like how it was before.
see something like the wiiguide : https://wii.guide/priiloader.html
