### ISSUE TITLE
Make an installer that runs from bootmii ( ceilingcat/mini )

### ISSUE THREAD

**Issue by weirdal3333** [DacoTaco/priiloader#305]
This is an enhancement idea for those who royally mess stuff up via video guide, and do not have a backup.

You can run files from within bootmii. The current installer requires an ios to be loaded, so it cannot be run in bootmii.

**Comment by DacoTaco** [comment]
hm, i think i get what youre trying to do.
however, i have some questions about your case.

you say it could be handy when royally messing up with a video guide. i assume this means that the wii no longer gives you a good video signal, except for bootmii @ boot2 ?
how would running the installer help here, knowing priiloader normally also gets video settings from the system config?

or do you mean video guide as in, like a youtube video? 
could you give more info about the system's state in which you would like to boot the installer from bootmii?

**Comment by TheTechRobo** [comment]
> you say it could be handy when royally messing up with a video guide. i assume this means that the wii no longer gives you a good video signal, except for bootmii @ boot2 ?
how would running the installer help here, knowing priiloader normally also gets video settings from the system config?

If they do mean that, they might mean that the Wii doesn't output a video signal, in which case Priiloader _could_ help (e.g. banner brick, bad SM, etc)

**Comment by Hallowizer** [comment]
> hm, i think i get what youre trying to do. however, i have some questions about your case.
> 
> you say it could be handy when royally messing up with a video guide. i assume this means that the wii no longer gives you a good video signal, except for bootmii @ boot2 ? how would running the installer help here, knowing priiloader normally also gets video settings from the system config?
> 
> or do you mean video guide as in, like a youtube video? could you give more info about the system's state in which you would like to boot the installer from bootmii?

"Video guide" typically refers to a guide delivered through a YouTube video. They're known to many homebrew communities for having bad/outdated information. I assume this suggestion has nothing to do with video output, but a more general brick situation.

**Comment by DacoTaco** [comment]
> "Video guide" typically refers to a guide delivered through a YouTube video. They're known to many homebrew communities for having bad/outdated information. I assume this suggestion has nothing to do with video output, but a more general brick situation.
yes, but that makes no sense. 
if you have a brick from such a situation, but still have access to bootmii then there would be no reason to have priiloader.
you can fix it all from within bootmii.

**Comment by DraconicNEO** [comment]
> > "Video guide" typically refers to a guide delivered through a YouTube video. They're known to many homebrew communities for having bad/outdated information. I assume this suggestion has nothing to do with video output, but a more general brick situation.
> 
> yes, but that makes no sense. if you have a brick from such a situation, but still have access to bootmii then there would be no reason to have priiloader. you can fix it all from within bootmii.

Not necessarily if the system menu and Homebrew channel are both borked then you won't be able to fix it all with bootmii unless you have a backup. Hence why being able to install or even just boot Priiloader from Bootmii would be very useful.

**Comment by Hallowizer** [comment]
If the HBC is screwed up, then it can be fixed with bootmini.elf, and the System Menu can be fixed from there. If every IOS is screwed up, then what is needed is a BootMii tool to reinstall IOSes from a disc or NUS. Also, unlike the System Menu, which Priiloader relies on, HBC can run under almost any IOS, and the installer automatically picks the latest working IOS.

**Comment by DacoTaco** [comment]
> > > "Video guide" typically refers to a guide delivered through a YouTube video. They're known to many homebrew communities for having bad/outdated information. I assume this suggestion has nothing to do with video output, but a more general brick situation.
> > 
> > yes, but that makes no sense. if you have a brick from such a situation, but still have access to bootmii then there would be no reason to have priiloader. you can fix it all from within bootmii.
>
> Not necessarily if the system menu and Homebrew channel are both borked then you won't be able to fix it all with bootmii > unless you have a backup. Hence why being able to install or even just boot Priiloader from Bootmii would be very useful.

i would argue you should use other tools to fix the nand then. maybe make a backup and use dolphin or another tool to fix said nand and restore it. 
or any other tool to fix any issues. i don't think priiloader is the best tool to help fix any issues. 
any other tool might do a better job, and it would need to be designed to be run on top of mini so it can be run from bootmii. 

im leaving this open for another few days so that if anyone could give me a case in which this would be needed, i could see to implement this but for now i see no purpose. @weirdal3333 , you wanted this. why?

**Comment by weirdal3333** [comment]
Priiloader's user interface is nicer than some of the other options. Not everyone has a PC, know how, or the tools to fix the system with. Booting an app with priiloader is a much *easier* option. It's not better, but it is easier. 
The normal version of priiloader needs an iOS to run. I may have misunderstood how it works, but I thought that removing the need for an iOS could possibly prevent some of the ios80 bricks that also screw up priiloader.

**Comment by DacoTaco** [comment]
thing is, the wii's boot process is as following : 
boot0 -> boot1 -> boot2 -> IOS -> IOS booting System Menu (which also boots priiloader when it is installed, as it is part of system menu).

installing priiloader from boot2 could be done, but i don't really see the point, as you'd still need a functioning IOS so priiloader could start, as it is IOS that starts system menu/Priiloader.

If IOS is broken, it means that it would need to run using mini (which is a bit of a pain) and somehow started from bootmii@boot2.
the only thing in priiloader that you could do was run a channel (since it would use boot2 to boot said title) or run something that also could run on mini, all other homebrew that priiloader could launch require IOS, and loading IOS at that point wouldn't help much.
in those cases i wonder what the point of having priiloader was to begin with?
it seems better to install or boot HBC from bootmii and go from there, as you will have more access to more stuff and more safe information online
